package chat.errors;



/**
 * code -19999~-10000
 */
public interface ChatErrorCodes {
	int CODE_CORE = -10000;

	int ERROR_ONLINESERVER_NOT_FOUND = CODE_CORE - 121;
	int ERROR_ONLINESERVER_UPDATE_FAILED = CODE_CORE - 122;
	int ERROR_ONLINESERVER_DELETE_FAILED = CODE_CORE - 123;
	int ERROR_ONLINESERVER_ADD_FAILED = CODE_CORE - 124;
	int ERROR_ONLINESERVER_QUERY_FAILED = CODE_CORE - 125;

	int ERROR_USERPRESENT_ADD_FAILED = CODE_CORE - 126;
	int ERROR_USERPRESENT_UPDATE_FAILED = CODE_CORE - 127;
	int ERROR_USERPRESENT_QUERY_FAILED = CODE_CORE - 128;
	int ERROR_USERPRESENT_NOTFOUND = CODE_CORE - 129;
	int ERROR_USERPRESENT_DELETE_FAILED = CODE_CORE - 130;
	int ERROR_ILLEGAL_PARAMETER = CODE_CORE - 131;
	int ERROR_SSH_CONNECT_FAILED = CODE_CORE - 132;
	int ERROR_SSH_EXEC_FAILED = CODE_CORE - 133;
	int ERROR_MESSAGEADD_FAILED = CODE_CORE - 134;
	int ERROR_ITERATOR_NULL = CODE_CORE - 135;
	int ERROR_UNKNOWN = CODE_CORE - 136;
	int ERROR_CORE_LOADRESOURCE_FAILED = CODE_CORE - 137;
	int ERROR_CORE_LOADRESOURCE_NOT_EXIST = CODE_CORE - 138;
	int ERROR_CORE_UPLOAD_DB_FAILED = CODE_CORE - 139;
	int ERROR_CORE_ZKDATA_PERSISTENT_FAILED = CODE_CORE - 140;
	int ERROR_CORE_ZKENSUREPATH_FAILED = CODE_CORE - 141;
	int ERROR_CORE_ZKGETDATA_FAILED = CODE_CORE - 142;
	int ERROR_CORE_ZKDATA_RESURRECT_FAILED = CODE_CORE - 143;
	int ERROR_CORE_ZKDATA_NEWINSTANCE_FAILED = CODE_CORE - 144;
	int ERROR_CORE_ZKADDWATCHEREX_FAILED = CODE_CORE - 145;
	int ERROR_ZK_DISCONNECTED = CODE_CORE - 146;
	int ERROR_CORE_SERVERPORT_ILLEGAL = CODE_CORE - 147;
	int ERROR_DAOINIT_FAILED = CODE_CORE - 148;
	int ERROR_ILLEGAL_ENCODE = CODE_CORE - 149;
	int ERROR_READCONTENT_FAILED = CODE_CORE - 150;
	int ERROR_UPLOAD_FAILED = CODE_CORE - 151;
	int ERROR_PARSE_REQUEST_FAILED = CODE_CORE - 152;
	int ERROR_ACCOUNTNAME_ILLEGAL = CODE_CORE - 153;
	int ERROR_ACCOUNTDOMAIN_ILLEGAL = CODE_CORE - 154;
	int ERROR_IO_FAILED = CODE_CORE - 155;
	int ERROR_LOGINUSER_NOT_FOUND = CODE_CORE - 156;
	int ERROR_BALANCER_NOT_READY = CODE_CORE - 157;
	int ERROR_CHARACTER_OVER_MAXIMUM_LIMITS = CODE_CORE - 158;
	int ERROR_TASKADD_FAILED = CODE_CORE - 159;
	int ERROR_FILE_EMPTY = CODE_CORE - 160;
	int ERROR_RPC_TYPE_NOMAPPING = CODE_CORE - 161;
	int ERROR_RPC_TYPE_NOSERVERADAPTER = CODE_CORE - 162;
	int ERROR_RPC_DISCONNECTED = CODE_CORE - 163;
	int ERROR_RPC_REQUESTTYPE_ILLEGAL = CODE_CORE - 164;
	int ERROR_RPC_REQUESTDATA_NULL = CODE_CORE - 165;
	int ERROR_RPC_PERSISTENT_FAILED = CODE_CORE - 166;
	int ERROR_RPC_RESURRECT_FAILED = CODE_CORE - 167;
	int ERROR_RMICALL_CONNECT_FAILED = CODE_CORE - 168;
	int ERROR_RMICALL_FAILED = CODE_CORE - 169;
	int ERROR_RPC_ILLEGAL = CODE_CORE - 170;
	int ERROR_RPC_TYPE_REQUEST_NOMAPPING = CODE_CORE - 171;
	int ERROR_GROOVY_PARSECLASS_FAILED = CODE_CORE - 172;
	int ERROR_GROOVY_UNKNOWN = CODE_CORE - 173;
	int ERROR_GROOVYSERVLET_SERVLET_NOT_INITIALIZED = CODE_CORE - 174;
	int ERROR_URL_VARIABLE_NULL = CODE_CORE - 175;
	int ERROR_URL_PARAMETER_NULL = CODE_CORE - 176;
	int ERROR_URL_HEADER_NULL = CODE_CORE - 177;
	int ERROR_JAVASCRIPT_LOADFILE_FAILED = CODE_CORE - 178;
	int ERROR_GROOY_CLASSCAST = CODE_CORE - 179;
	int ERROR_METHODMAPPING_METHOD_NULL = CODE_CORE - 180;
	int ERROR_METHODMAPPING_INSTANCE_NULL = CODE_CORE - 181;
	int ERROR_METHODMAPPING_ACCESS_FAILED = CODE_CORE - 182;
	int ERROR_METHODMAPPING_INVOKE_FAILED = CODE_CORE - 183;
	int ERROR_METHODMAPPING_INVOKE_UNKNOWNERROR = CODE_CORE - 184;
	int ERROR_POST_FAILED = CODE_CORE - 185;
	int ERROR_LANSERVERS_NOSERVERS = CODE_CORE - 186;
	int ERROR_RPC_CALLREMOTE_FAILED = CODE_CORE - 187;
	int ERROR_METHODRESPONSE_NULL = CODE_CORE - 188;
	int ERROR_METHODREQUEST_CRC_ILLEGAL = CODE_CORE - 189;
	int ERROR_METHODREQUEST_METHODNOTFOUND = CODE_CORE - 190;
	int ERROR_RPC_DECODE_FAILED = CODE_CORE - 191;
	int ERROR_RPC_ENCODER_NOTFOUND = CODE_CORE - 192;
	int ERROR_RPC_ENCODER_NULL = CODE_CORE - 193;
	int ERROR_RPC_ENCODE_FAILED = CODE_CORE - 194;
	int ERROR_METHODREQUEST_SERVICE_NOTFOUND = CODE_CORE - 195;
	int ERROR_METHODREQUEST_SKELETON_NULL = CODE_CORE - 196;
	int ERROR_METHODREQUEST_SERVICE_NULL = CODE_CORE - 197;
	int ERROR_SERVICENAME_DUPLICATE = CODE_CORE - 198;
	int ERROR_DEPLOYSERVICEVERSION_NULL = CODE_CORE - 199;
	int ERROR_SERVICEVERSION_EMPTY = CODE_CORE - 200;

	int ERROR_SDOCKER_QUERY_FAILED = CODE_CORE - 201;
	int ERROR_GET_FAILED = CODE_CORE - 202;
	int ERROR_NO_REMOTESERVERS= CODE_CORE - 203;
	int ERROR_NO_BASERUNTIME= CODE_CORE - 204;
	int ERROR_NO_SOURCEFILE= CODE_CORE - 205;
	int ERROR_DISCOVERY_NOTFOUND= CODE_CORE - 206;
	int ERROR_ASYNC_ERROR= CODE_CORE - 207;
	int ERROR_ASYNC_TIMEOUT= CODE_CORE - 208;
	int ERROR_QUARTZ_ADDFAILED =  CODE_CORE - 209;
	int ERROR_QUARTZ_CANCELEDFAILED= CODE_CORE - 210;
	int ERROR_SERVER_CONNECT_FAILED= CODE_CORE - 211;
	int ERROR_SERVER_NOT_FOUND = CODE_CORE - 212;
	/*******************ehcache******************/
	int ERROR_CREATE_CACHE= CODE_CORE - 212;
	int ERROR_CACHE_ILLEGAL_PARAMETER= CODE_CORE - 213;
	int ERROR_CACHE_PUT= CODE_CORE - 214;
	int ERROR_CACHE_GET= CODE_CORE - 215;

	int ERROR_REMOTEERVICE_CONCURRENTLIMIT= CODE_CORE - 216;
	int ERROR_ASYNC_NEEDRETRY= CODE_CORE - 217;

	int ERROR_REMOTE_RPC_FAILED= CODE_CORE - 218;
	int ERROR_CALLREMOTE_BY_HTTP_FAILED = CODE_CORE - 219;
	int ERROR_MAVEN_INSTALL_ERROR= CODE_CORE - 220;
	int ERROR_SOURCE_DWONLOAD_FAILED= CODE_CORE - 221;
	int ERROR_CLASSLOADER_CREATE_FAILED= CODE_CORE - 222;
	int ERROR_REFLECT = CODE_CORE - 223;
	int ERROR_BOOT = CODE_CORE - 224;
}
