package oceanus.sdk.core.discovery.errors;



/**
 * code -39999~-30000
 */
public interface CoreErrorCodes {


	int CODE_CORE = -30000;//0~999

	int ERROR_RPC_ILLEGAL = CODE_CORE + 1;

	int ERROR_SCRIPT_UNZIP_FAILED = CODE_CORE + 2;
	int ERROR_LANID_ILLEGAL = CODE_CORE + 3;
	int ERROR_REDIS = CODE_CORE + 4;
	int ERROR_KAFKA_CONFCENT_ILLEGAL = CODE_CORE + 5;
	int ERROR_RPC_TYPE_NOSERVERADAPTER = CODE_CORE +6;
	int ERROR_RPC_TYPE_NOMAPPING = CODE_CORE + 7;
	int ERROR_LOADPROPERTIES_FAILED = CODE_CORE + 8;
	int ERROR_GROOVYCLOUDCONFIG_ILLEGAL = CODE_CORE + 9;
	int ERROR_LAN_FAILED = CODE_CORE + 10;
	int ERROR_CANT_FIND_CLASS = CODE_CORE + 11;
	int ERROR_RPC_SERVER_CALL_FAILED = CODE_CORE + 12;

	int ERROR_LOCK = -35000;
	int ERROR_LOCK_CAN_NOT_FOUND = ERROR_LOCK + 1;
	int ERROR_LOCK_VERIFY_FIELD = ERROR_LOCK + 2;
	int ERROR_ZOOKEEPER_CLIENT_NULL = ERROR_LOCK + 3;
	int ERROR_ZOOKEEPER_EXECUTE_FAILED = ERROR_LOCK + 4;

}
